Lab4/lab4/account/urls.py
from django.urls import path
from .views import signup

app_name = 'account'
urlpatterns = [
    path('signup', signup, name='signup'),
]

Lab4/lab4/actor/urls.py
from django.urls import path, include
from .views import actors_list, actor_details, actor_create, actor_delete, actor_update

app_name = 'actor'
urlpatterns = [
    path('list', actors_list, name='list'),
    path('create', actor_create, name='create'),
    path('details/<int:pk>', actor_details, name='details'),
    path('update/<int:pk>',actor_update, name='update'),
    path('delete/<int:pk>', actor_delete, name='delete'),
]

Lab4/lab4/director/urls.py
from django.urls import path, include
from .views import directors_list, director_details, director_create, director_delete, director_update

app_name = 'director'
urlpatterns = [
    path('list', directors_list, name='list'),
    path('create', director_create, name='create'),
    path('details/<int:pk>', director_details, name='details'),
    path('update/<int:pk>',director_update, name='update'),
    path('delete/<int:pk>', director_delete, name='delete'),
]

Lab4/lab4/lab4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),
    path('api/v1/account/', include('account.api.v1.urls')),
    path('todo/', include('todo.urls')),
    path('movie/', include('movie.urls')),
    path('api/v1/movie/', include('movie.api.v1.urls')),
    path('actor/', include('actor.urls')),
    path('api/v1/actor/', include('actor.api.v1.urls')),
    path('billing/', include('billing.urls')),
    path('director/', include('director.urls')),
]

# Works Only in Debug mode
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Lab4/lab4/movie/urls.py
from django.urls import path, include
from .views import movies_list, movie_details, movie_create, movie_delete, movie_update

app_name = 'movie'
urlpatterns = [
    path('list', movies_list, name='list'),
    path('create', movie_create, name='create'),
    path('details/<int:pk>', movie_details, name='details'),
    path('update/<int:pk>',movie_update, name='update'),
    path('delete/<int:pk>', movie_delete, name='delete'),
]

Lab4/lab4/todo/urls.py
from django.urls import path, include
from .views import todo_details, todo_home, todo_delete, todo_edit, todo_done, todo_undone, todo_update

app_name = 'todo'
urlpatterns = [
    path('', todo_home, name='home'),
    path('details/<str:todo_name>', todo_details, name='details'),
    path('edit/<str:todo_name>', todo_edit, name='edit'),
    path('update/<str:todo_name>',todo_update, name='update'),
    path('done/<str:todo_name>', todo_done, name='done'),
    path('undone/<str:todo_name>', todo_undone, name='undone'),
    path('delete/<str:todo_name>', todo_delete, name='delete'),
]

Lab4/lab4/todo/models.py
from turtle import update
from django.db import models

class Todo(models.Model):
    name = models.fields.CharField(verbose_name="Todo Name", max_length=100)#, unique=True)
    priority = models.fields.IntegerField(verbose_name="Todo Priority", default=1)
    todo_date = models.fields.DateTimeField(verbose_name="Todo Date", default='2019-01-01 10:10') 
    is_done = models.fields.BooleanField(verbose_name="Todo Done", default=False)
    description = models.fields.TextField(verbose_name="Todo Description", default='', max_length=500)
    creation_time = models.fields.DateTimeField(verbose_name="Creation Time",auto_now_add=True)
    update_time = models.fields.DateTimeField(verbose_name="Update Time", auto_now=True)

    def __str__(self):
        return f"Todo: {self.name} At Time: {self.creation_time}"

    class Meta:
        verbose_name = "Todo"
        verbose_name_plural = "Todos"
        ordering = ['-id']

class Task(models.Model):
    name = models.fields.CharField(verbose_name="Task Name", max_length=100)
    todo = models.ForeignKey('todo', on_delete=models.CASCADE)#on_delete=models.SET_NULL, null=True)

# class Actor(models.Model):
#     pass

# class Movie(models.Model):
#     actors = models.ManyToManyField('actor')
#     directors = models.ManyToManyField('director')
#     serial_number = models.OneToOneField('serial_number', on_delete=models.CASCADE)

# class Director(models.Model):
#     pass

# class serial(models.Model):
#     pass

Lab4/lab4/todo/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
# from django.http.response import JsonResponse
from .models import Todo, Task
from pprint import pprint

my_todo_list = {
    'one': {'name': 'laravel', 'priority': 1, 'is_done': False, 'description': 'laravel is a web framework for PHP'},
    'two': {'name': 'django', 'priority': 2, 'is_done': False, 'description': 'django is a web framework for Python'},
    'three': {'name': 'nodejs', 'priority': 3, 'is_done': False, 'description': 'nodejs is a web framework for JavaScript'},
}

def todo_home(request):
    # pprint(vars(request))
    # return HttpResponse("Todo Home")
    return render(request, 'todo/todo.html', context={'my_todo_list': my_todo_list})

def todo_details(request, **kwargs):
    target_todo_name = kwargs.get('todo_name')
    todo_details = my_todo_list.get(target_todo_name)
    return render(request, 'todo/todo_details.html', context={'my_todo': todo_details})


def todo_edit(request,**kwargs):
    target_todo_name = kwargs.get('todo_name')
    return render(request, 'todo/todo_edit.html', context={'my_todo': target_todo_name})

def todo_update(request,**kwargs):
    task_name=kwargs.get('todo_name')
    my_target_todo = my_todo_list.get(task_name)
    my_target_todo['is_done'] = True
    my_target_todo['name'] = 'updated'
    return redirect(reverse('todo:home'))

def todo_done(request, **kwargs):
    target_todo_name = kwargs.get('todo_name')
    my_todo_list.get(target_todo_name)['is_done'] = True
    return redirect(reverse('todo:home'))

def todo_undone(request, **kwargs):
    target_todo_name = kwargs.get('todo_name')
    my_todo_list.get(target_todo_name)['is_done'] = False
    return redirect(reverse('todo:home'))

def todo_delete(request, **kwargs):
    target_todo_name = kwargs.get('todo_name')
    if my_todo_list.get(target_todo_name)['is_done']:
        my_todo_list.pop(target_todo_name)
        return redirect(reverse('todo:home'))
    else:
        return render(request, 'todo/todo.html', context={'my_todo_list': my_todo_list, 'warning_message': 'You cannot delete a todo that is not done yet.'})

Lab4/lab4/todo/templates/todo/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'generic_static/css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
        body {
            padding-top: 5px;
            color: white;
            background-color: black;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <a class="navbar-brand" href="#">{{user.username}}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'todo:home' %}">TODO List</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'actor:list' %}">Actors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'director:list' %}">Directors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'movie:list' %}">Movies</a>
                </li>
            </ul>
            {% if request.user.is_authenticated %}
            <a class="btn btn-outline-danger my-2 my-sm-0  mr-sm-2" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="btn btn-outline-success my-2 my-sm-0  mr-sm-2" href="{% url 'login' %}">Login</a>
            <a class="btn btn-outline-primary my-2 my-sm-0  mr-sm-2" href="{% url 'account:signup' %}">Signup</a>
            {% endif %}
        </div>
    </nav>
    {% block body_content %}
    {% endblock %}
    <script src="{% static 'generic_static/js/bootstrap.bundle.min.js'%}"></script>
</body>

</html>

Lab4/lab4/todo/templates/todo/todo.html
{% extends 'todo/base.html' %}
{% load custom_tags %}

{% block title %}TODO List{% endblock %}
{% block body_content %}
<h1 align="center">TODO List</h1>
{% comment %}
{% my_custom_tag as my_var %}
My var: {{my_var}}
{% endcomment %}
{% if warning_message %}
<div align="center" class="alert alert-warning">{{warning_message}}</div>
{% endif %}
<table class="table table-bordered table-hover" style="color: white;">
    <thead align="center" style="color: green; font-weight: bold; font-size: larger;">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Priority</th>
            <th>Finished</th>
            <th>Description</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for todo, value in my_todo_list.items %}
        <tr>
            <td>{{ todo|upper }}</td>
            <td>{{ value.name|title }}</td>
            <td>{{ value.priority }}</td>
            <td>{{ value.is_done|title }}</td>
            <td>{{ value.description|my_filter }}</td>
            <td>
                <center>
                    <a href="{% url 'todo:details' todo %}" class="btn btn-info">View</a>
                    <a href="{% url 'todo:edit' todo %}" class="btn btn-primary">Edit</a>
                    {% if value.is_done == False %}
                    <a href="{% url 'todo:done' todo %}" class="btn btn-success">Done</a>
                    {% else %}
                    <a href="{% url 'todo:undone' todo %}" class="btn btn-warning">Undone</a>
                    {% endif %}
                    <a href="{% url 'todo:delete' todo %}" class="btn btn-danger">Delete</a>
                </center>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

Lab4/lab4/todo/templates/todo/todo_details.html
{% extends 'todo/base.html' %}

{% block title %}TODO details{% endblock %}

{% block body_content %}
<div class="card my-3" style="color: black;">
    <h5 class="card-header">TODO Info</h5>
    <div class="card-body">
        <div>
            <span style="font-size: 1.2rem; font-weight: bold">Name: </span>
            <p class="card-text">{{my_todo.name | title}}</p>
        </div>
        <div>
            <span style="font-size: 1.2rem; font-weight: bold">Priority: </span>
            <p class="card-text">{{my_todo.priority}}</p>
        </div>
        <div>
            <span style="font-size: 1.2rem; font-weight: bold">Description: </span>
            <p class="card-text">{{my_todo.description}}</p>
        </div>
        <div>
            <span style="font-size: 1.2rem; font-weight: bold">Finished: </span>
            <p class="card-text">{{my_todo.is_done}}</p>
        </div>
    </div>
    <a href="{% url 'todo:home' %}" class="btn btn-secondary">Back Home</a>
</div>
{% endblock %}

Lab4/lab4/todo/templates/todo/todo_edit.html
{% extends 'todo/base.html' %}

{% block title %}TODO edit{% endblock %}

{% block body_content %}
<div class="card bg-info" style="width: 25rem;">
    <h4>Coming Soon...</h4>
    <a href="{% url 'todo:update' my_todo %}" class="btn btn-success">update</a>    
</div>
{% endblock %}