Lab4/lab4/lab4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),
    path('api/v1/account/', include('account.api.v1.urls')),
    path('todo/', include('todo.urls')),
    path('movie/', include('movie.urls')),
    path('api/v1/movie/', include('movie.api.v1.urls')),
    path('actor/', include('actor.urls')),
    path('api/v1/actor/', include('actor.api.v1.urls')),
    path('billing/', include('billing.urls')),
    path('director/', include('director.urls')),
]

# Works Only in Debug mode
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Lab4/lab4/movie/api/v1/urls.py
from django.urls import path, include
from .views import hello_drf, movie_home, MovieHome, movie_details, movie_create, movie_update, movie_delete

app_name = 'movie-rest-v1'
urlpatterns = [
    path('hello-drf', hello_drf, name='ho-def'),
    path('', movie_home, name='list'),
    path('generics', MovieHome.as_view(), name='generics-list'),
    path('<int:movie_id>', movie_details, name='details'),
    path('create', movie_create, name='create'),
    path('<int:movie_id>/update', movie_update, name='update'),
    path('<int:movie_id>/delete', movie_delete, name='delete'),
]

Lab4/lab4/movie/urls.py
from django.urls import path, include
from .views import movies_list, movie_details, movie_create, movie_delete, movie_update

app_name = 'movie'
urlpatterns = [
    path('list', movies_list, name='list'),
    path('create', movie_create, name='create'),
    path('details/<int:pk>', movie_details, name='details'),
    path('update/<int:pk>',movie_update, name='update'),
    path('delete/<int:pk>', movie_delete, name='delete'),
]

Lab4/lab4/movie/models.py
from django.db import models


class Movie(models.Model):
    active = models.fields.BooleanField(verbose_name='Active', default=False)
    name = models.fields.CharField(verbose_name='Movie Name', max_length=50)
    production_year = models.fields.DateField(verbose_name='Production Year', null=True)
    actors = models.ManyToManyField('actor.actor')
    director = models.ForeignKey('director.director', on_delete=models.CASCADE, null=True)
    creation_time = models.fields.DateTimeField(verbose_name="Creation Time",auto_now_add=True)
    update_time = models.fields.DateTimeField(verbose_name="Update Time", auto_now=True)

    def __str__(self):
        return self.name

Lab4/lab4/movie/forms.py
from django.forms import ModelForm
from django import forms
from .models import Movie

class MovieForm(ModelForm):
    # def clean(self):
    #     if self.cleaned_data.get('watch_count'):
    #         if self.cleaned_data.get('watch_count') < 10:
    #             raise forms.ValidationError("Watch count is too low")

    #     return self.cleaned_data

    class Meta:
        model = Movie
        fields = '__all__'

Lab4/lab4/movie/api/v1/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.permissions import IsAuthenticated, AllowAny, IsAuthenticatedOrReadOnly, IsAdminUser
from rest_framework.authentication import TokenAuthentication, SessionAuthentication, BasicAuthentication
from rest_framework.generics import ListAPIView, UpdateAPIView, ListCreateAPIView
from movie.models import Movie
from .serializers import MovieSerializer, MovieCreateSerializer, MovieUpdateSerializer
from .permissions import MyPermission

class MovieHome(ListAPIView):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer

class MovieUpdate(UpdateAPIView):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer

@api_view(['GET'])
def hello_drf(request):
    return Response(data={"message":"Hello"}, status=status.HTTP_200_OK)

@api_view(['GET'])
def movie_home(request):
    movie_object = Movie.objects.all()
    serializer = MovieSerializer(movie_object, many=True)
    return Response(data=serializer.data, status=status.HTTP_200_OK)

@api_view(['GET'])
def movie_details(request, movie_id):
    movie = Movie.objects.get(pk=movie_id)
    serializer = MovieSerializer(movie)
    return Response(data=serializer.data, status=status.HTTP_200_OK)

@api_view(['POST'])
def movie_create(request):
    response = {'data':{}, 'status':status.HTTP_400_BAD_REQUEST}
    serializer = MovieCreateSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save()
        response['data'] = serializer.data
        response['status'] = status.HTTP_201_CREATED
        # return Response(data=serializer.data, status=status.HTTP_201_CREATED)
    else:
        response['data'] = serializer.errors
    return Response(**response)
    # return Response(data=serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['PUT','PATCH'])
def movie_update(request, movie_id):
    response = {'data':{}, 'status':status.HTTP_400_BAD_REQUEST}
    # movie = Movie.objects.filter(pk=movie_id).first()
    movie = Movie.objects.get(pk=movie_id)
    if request.method == 'PUT':
        serializer = MovieUpdateSerializer(instance=movie, data=request.data)
    else:
        serializer = MovieUpdateSerializer(instance=movie, data=request.data, partial=True)
    if serializer.is_valid():
        serializer.save()
        response['data'] = serializer.data
        response['status'] = status.HTTP_201_CREATED
    else:
        response['data'] = serializer.errors
    return Response(**response)

@api_view(['DELETE'])
@authentication_classes([TokenAuthentication])
@permission_classes([IsAuthenticated])
def movie_delete(request, movie_id):
    Movie.objects.get(pk=movie_id).delete()
    return Response(data={"message": "Deleted Successfully"}, status=status.HTTP_204_NO_CONTENT)

Lab4/lab4/movie/views.py
from django.shortcuts import render, redirect, reverse
from .models import Movie
from .forms import MovieForm
from django.contrib.auth.decorators import login_required

def movies_list(request):
    movies = Movie.objects.all()
    return render(request, template_name='movie/movies_list.html', context={'movies': movies})

@login_required
def movie_create(request):
    if request.method == 'POST':
        form = MovieForm(data= request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('movie:list'))
    elif request.method == 'GET':
        form = MovieForm()  
    return render(request, template_name='movie/movie_create.html', context={'form': form})

def movie_details(request, pk):
    movie = Movie.objects.get(pk=pk)
    return render(request, template_name='movie/movie_details.html', context={'movie': movie})

def movie_update(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.method == 'POST':
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return redirect(reverse('movie:list'))
    elif request.method == 'GET':
        form = MovieForm(instance=movie)
        return render(request, template_name='movie/movie_update.html', context={'form': form, 'movie': movie})

def movie_delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    movie.delete()
    return redirect(reverse('movie:list'))

Lab4/lab4/movie/templates/Movie/movie_create.html
{% extends 'general_templates/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Create Movie{% endblock %}
{% block body_content %}

<h1 align="center">Add Movie</h1>

<form action="{% url 'movie:create' %}" method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <center>
        <button type="submit" class="btn btn-success">Create</button>
        <a href="{% url 'movie:list' %}" class="btn btn-secondary">Back</a>
    </center>
</form>
{% endblock %}

Lab4/lab4/movie/templates/Movie/movie_details.html
{% extends 'general_templates/base.html' %}

{% block title %}Movie details{% endblock %}

{% block body_content %}
<div class="card my-3" style="color: black;">
    <h5 class="card-header">Movie Info</h5>
    <div class="card-body">
        <div>
            <span style="font-size: 1.2rem; font-weight: bold">Name: </span>
            <p class="card-text">{{movie.name | title}}</p>
        </div>
        <div>
            <span style="font-size: 1.2rem; font-weight: bold">Production Year: </span>
            <p class="card-text">{{movie.production_year}}</p>
        </div>
        <div>
            <span style="font-size: 1.2rem; font-weight: bold">Actors: </span>
            <p class="card-text">
                <ul>
                    {% for actor in movie.actors.all %}
                        <li>{{ actor }}</li>
                    {% endfor %}
                </ul>
            </p>

        </div>
        <div>
            <span style="font-size: 1.2rem; font-weight: bold">Director: </span>
            <p class="card-text">{{movie.director}}</p>
        </div>
    </div>
    <a href="{% url 'movie:list' %}" class="btn btn-secondary">Back Home</a>
</div>
{% endblock %}

Lab4/lab4/movie/templates/Movie/movie_update.html
{% extends 'general_templates/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Movie Update{% endblock %}
{% block body_content %}

<h1 align="center">Add Movie</h1>

<form action="{% url 'movie:update' movie.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <center>
        <button type="submit" class="btn btn-success">Edit</button>
        <a href="{% url 'movie:list' %}" class="btn btn-secondary">Back</a>
    </center>
</form>
{% endblock %}

Lab4/lab4/movie/templates/Movie/movies_list.html
{% extends 'general_templates/base.html' %}

{% block title %}Movies List{% endblock %}
{% block body_content %}
<h1 align="center">Movies List</h1>

<table class="table table-bordered table-hover" style="color: white;">
    <thead align="center" style="color: green; font-weight: bold; font-size: larger;">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Production Year</th>
            <th>Director</th>
            <th><a class="btn btn-success" href="{% url 'movie:create' %}">Add Movie</a></th>
        </tr>
    </thead>
    <tbody>
        {% for movie in movies %}
        <tr>
            <td>{{ movie.id }}</td>
            <td>{{ movie|title }}</td>
            <td>{{ movie.production_year }}</td>
            <td>{{ movie.director }}</td>
            {% if request.user.is_authenticated %}
            <td>
                <center>
                    <a href="{% url 'movie:details' movie.id %}" class="btn btn-info">View</a>
                    <a href="{% url 'movie:update' movie.id %}" class="btn btn-primary">Edit</a>
                    <a href="{% url 'movie:delete' movie.id %}" class="btn btn-danger">Delete</a>
                </center>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}