Lab4/lab4/account/urls.py
from django.urls import path
from .views import signup

app_name = 'account'
urlpatterns = [
    path('signup', signup, name='signup'),
]

Lab4/lab4/actor/urls.py
from django.urls import path, include
from .views import actors_list, actor_details, actor_create, actor_delete, actor_update

app_name = 'actor'
urlpatterns = [
    path('list', actors_list, name='list'),
    path('create', actor_create, name='create'),
    path('details/<int:pk>', actor_details, name='details'),
    path('update/<int:pk>',actor_update, name='update'),
    path('delete/<int:pk>', actor_delete, name='delete'),
]

Lab4/lab4/lab4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),
    path('api/v1/account/', include('account.api.v1.urls')),
    path('todo/', include('todo.urls')),
    path('movie/', include('movie.urls')),
    path('api/v1/movie/', include('movie.api.v1.urls')),
    path('actor/', include('actor.urls')),
    path('api/v1/actor/', include('actor.api.v1.urls')),
    path('billing/', include('billing.urls')),
    path('director/', include('director.urls')),
]

# Works Only in Debug mode
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Lab4/lab4/movie/urls.py
from django.urls import path, include
from .views import movies_list, movie_details, movie_create, movie_delete, movie_update

app_name = 'movie'
urlpatterns = [
    path('list', movies_list, name='list'),
    path('create', movie_create, name='create'),
    path('details/<int:pk>', movie_details, name='details'),
    path('update/<int:pk>',movie_update, name='update'),
    path('delete/<int:pk>', movie_delete, name='delete'),
]

Lab4/lab4/todo/urls.py
from django.urls import path, include
from .views import todo_details, todo_home, todo_delete, todo_edit, todo_done, todo_undone, todo_update

app_name = 'todo'
urlpatterns = [
    path('', todo_home, name='home'),
    path('details/<str:todo_name>', todo_details, name='details'),
    path('edit/<str:todo_name>', todo_edit, name='edit'),
    path('update/<str:todo_name>',todo_update, name='update'),
    path('done/<str:todo_name>', todo_done, name='done'),
    path('undone/<str:todo_name>', todo_undone, name='undone'),
    path('delete/<str:todo_name>', todo_delete, name='delete'),
]

Lab4/lab4/templates/general_templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'generic_static/css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
        body {
            padding-top: 5px;
            color: white;
            background-color: black;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <a class="navbar-brand" href="#">{{user.username}}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'todo:home' %}">TODO List</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'actor:list' %}">Actors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'director:list' %}">Directors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'movie:list' %}">Movies</a>
                </li>
            </ul>
            {% if request.user.is_authenticated %}
            <a class="btn btn-outline-danger my-2 my-sm-0  mr-sm-2" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="btn btn-outline-success my-2 my-sm-0  mr-sm-2" href="{% url 'login' %}">Login</a>
            <a class="btn btn-outline-primary my-2 my-sm-0  mr-sm-2" href="{% url 'account:signup' %}">Signup</a>
            {% endif %}
        </div>
    </nav>
    {% block body_content %}
    {% endblock %}
    <script src="{% static 'generic_static/js/bootstrap.bundle.min.js'%}"></script>
</body>

</html>