Lab4/lab4/actor/api/v1/urls.py
from django.urls import path, include
from .views import hello_drf, actor_home, ActorHome, actor_details, actor_create, actor_update, actor_delete

app_name = 'actor-rest-v1'
urlpatterns = [
    path('hello-drf', hello_drf, name='ho-def'),
    path('', actor_home, name='list'),
    path('generics', ActorHome.as_view(), name='generics-list'),
    path('<int:actor_id>', actor_details, name='details'),
    path('create', actor_create, name='create'),
    path('<int:actor_id>/update', actor_update, name='update'),
    path('<int:actor_id>/delete', actor_delete, name='delete'),
]

Lab4/lab4/actor/urls.py
from django.urls import path, include
from .views import actors_list, actor_details, actor_create, actor_delete, actor_update

app_name = 'actor'
urlpatterns = [
    path('list', actors_list, name='list'),
    path('create', actor_create, name='create'),
    path('details/<int:pk>', actor_details, name='details'),
    path('update/<int:pk>',actor_update, name='update'),
    path('delete/<int:pk>', actor_delete, name='delete'),
]

Lab4/lab4/lab4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),
    path('api/v1/account/', include('account.api.v1.urls')),
    path('todo/', include('todo.urls')),
    path('movie/', include('movie.urls')),
    path('api/v1/movie/', include('movie.api.v1.urls')),
    path('actor/', include('actor.urls')),
    path('api/v1/actor/', include('actor.api.v1.urls')),
    path('billing/', include('billing.urls')),
    path('director/', include('director.urls')),
]

# Works Only in Debug mode
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Lab4/lab4/actor/models.py
from django.db import models

class Actor(models.Model):
    # NATIONALITIES = (
    #     ('eg', 'Egyptian'),
    #     ('ksa', 'Saudi Arabian'),
    #     ('kuwait', 'Kuwait Citizen'),
    # )
    GENDER = (
        ('Male','Male'),
        ('Female','Female'),
    )
    name = models.fields.CharField(verbose_name="Actor", max_length=100)
    gender = models.fields.CharField(choices=GENDER, max_length=6, default='Male')
    # age = models.fields.IntegerField()
    # nationality = models.fields.CharField(choices=NATIONALITIES, max_length=6)
    profile_pic = models.ImageField(upload_to='actor')

    def __str__(self):
        return self.name

Lab4/lab4/actor/forms.py
from django.forms import ModelForm
from .models import Actor

class ActorForm(ModelForm):
    class Meta:
        model = Actor
        fields = '__all__'

Lab4/lab4/actor/api/v1/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.permissions import IsAuthenticated, AllowAny, IsAuthenticatedOrReadOnly, IsAdminUser
from rest_framework.authentication import TokenAuthentication, SessionAuthentication, BasicAuthentication
from rest_framework.generics import ListAPIView, UpdateAPIView, ListCreateAPIView
from actor.models import Actor
from .serializers import ActorSerializer, ActorCreateUpdateSerializer

class ActorHome(ListAPIView):
    queryset = Actor.objects.all()
    serializer_class = ActorSerializer

class ActorUpdate(UpdateAPIView):
    queryset = Actor.objects.all()
    serializer_class = ActorSerializer

@api_view(['GET'])
def hello_drf(request):
    return Response(data={"message":"Hello"}, status=status.HTTP_200_OK)

@api_view(['GET'])
def actor_home(request):
    actor_object = Actor.objects.all()
    serializer = ActorSerializer(actor_object, many=True)
    return Response(data=serializer.data, status=status.HTTP_200_OK)

@api_view(['GET'])
def actor_details(request, actor_id):
    actor = Actor.objects.get(pk=actor_id)
    serializer = ActorSerializer(actor)
    return Response(data=serializer.data, status=status.HTTP_200_OK)

@api_view(['POST'])
def actor_create(request):
    response = {'data':{}, 'status':status.HTTP_400_BAD_REQUEST}
    serializer = ActorCreateUpdateSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save()
        response['data'] = serializer.data
        response['status'] = status.HTTP_201_CREATED
        # return Response(data=serializer.data, status=status.HTTP_201_CREATED)
    else:
        response['data'] = serializer.errors
    return Response(**response)
    # return Response(data=serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['PUT','PATCH'])
def actor_update(request, actor_id):
    response = {'data':{}, 'status':status.HTTP_400_BAD_REQUEST}
    # actor = Actor.objects.filter(pk=actor_id).first()
    actor = Actor.objects.get(pk=actor_id)
    if request.method == 'PUT':
        serializer = ActorCreateUpdateSerializer(instance=actor, data=request.data)
    else:
        serializer = ActorCreateUpdateSerializer(instance=actor, data=request.data, partial=True)
    if serializer.is_valid():
        serializer.save()
        response['data'] = serializer.data
        response['status'] = status.HTTP_201_CREATED
    else:
        response['data'] = serializer.errors
    return Response(**response)

@api_view(['DELETE'])
@authentication_classes([TokenAuthentication])
@permission_classes([IsAuthenticated])
def actor_delete(request, actor_id):
    Actor.objects.get(pk=actor_id).delete()
    return Response(data={"message": "Deleted Successfully"}, status=status.HTTP_204_NO_CONTENT)

Lab4/lab4/actor/views.py
from re import A
from django.shortcuts import redirect, render, reverse
from .models import Actor
from .forms import ActorForm

def actors_list(request):
    actors = Actor.objects.all()
    return render(request, template_name='actor/actors_list.html', context={'actors': actors})

def actor_create(request):
    if request.method == 'POST':
        form = ActorForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse('actor:list'))
    elif request.method == 'GET':
        form = ActorForm()  
    return render(request, template_name='actor/actor_create.html', context={'form': form})

def actor_details(request, pk):
    actor = Actor.objects.get(pk=pk)
    return render(request, template_name='actor/actor_details.html', context={'actor': actor})

def actor_update(request, pk):
    actor = Actor.objects.get(pk=pk)
    if request.method == 'POST':
        form = ActorForm(data=request.POST, files=request.FILES, instance=actor)
        if form.is_valid():
            form.save()
            return redirect(reverse('actor:list'))
    elif request.method == 'GET':
        form = ActorForm(instance=actor)
        return render(request, template_name='actor/actor_update.html', context={'form': form, 'actor': actor})

def actor_delete(request, pk):
    actor = Actor.objects.get(pk=pk)
    actor.delete()
    return redirect(reverse('actor:list'))

Lab4/lab4/actor/templates/actor/actor_create.html
{% extends 'general_templates/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Add Actor{% endblock %}
{% block body_content %}

<h1 align="center">Add Actor</h1>

<form action="{% url 'actor:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <center>
        <button type="submit" class="btn btn-success">Create</button>        
        <a href="{% url 'actor:list' %}" class="btn btn-secondary">Back</a>
    </center>
</form>
{% endblock %}

Lab4/lab4/actor/templates/actor/actor_details.html
{% extends 'general_templates/base.html' %}

{% block title %}Actor details{% endblock %}

{% block body_content %}
<div class="card my-3" style="color: black;">
    <h5 class="card-header">Actor Info</h5>
    <div class="card-body">
        <img height="20%" width="20%" src="{{request.scheme}}://{{request.get_host}}{{actor.profile_pic.url}}">
        <div>
            <span style="font-size: 1.2rem; font-weight: bold">Name: </span>
            <p class="card-text">{{actor.name | title}}</p>
        </div>
        <div>
            <span style="font-size: 1.2rem; font-weight: bold">Gender: </span>
            <p class="card-text">{{actor.gender}}</p>
        </div>
    </div>
    <a href="{% url 'actor:list' %}" class="btn btn-secondary">Back Home</a>
</div>
{% endblock %}

Lab4/lab4/actor/templates/actor/actor_update.html
{% extends 'general_templates/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Actor Update{% endblock %}
{% block body_content %}

<h1 align="center">Add Actor</h1>

<form action="{% url 'actor:update' actor.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <center>
        <button type="submit" class="btn btn-success">Edit</button>
        <a href="{% url 'actor:list' %}" class="btn btn-secondary">Back</a>
    </center>
</form>
{% endblock %}

Lab4/lab4/actor/templates/actor/actors_list.html
{% extends 'general_templates/base.html' %}

{% block title %}Actors List{% endblock %}
{% block body_content %}
<h1 align="center">Actors List</h1>

<table class="table table-bordered table-hover" style="color: white;">
    <thead align="center" style="color: green; font-weight: bold; font-size: larger;">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Gender</th>
            <th>Profile Picture</th>
            <th><a class="btn btn-success" href="{% url 'actor:create' %}">Add Actor</a></th>
        </tr>
    </thead>
    <tbody>
        {% for actor in actors %}
        <tr>
            <td>{{ actor.id }}</td>
            <td>{{ actor|title }}</td>
            <td>{{ actor.gender }}</td>
            <td>
                <center>
                    <img height="20%" width="20%" src="{{request.scheme}}://{{request.get_host}}{{actor.profile_pic.url}}">
                </center>
            </td>
            <td>
                <center>
                    <a href="{% url 'actor:details' actor.id %}" class="btn btn-info">View</a>
                    <a href="{% url 'actor:update' actor.id %}" class="btn btn-primary">Edit</a>
                    <a href="{% url 'actor:delete' actor.id %}" class="btn btn-danger">Delete</a>
                </center>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}